---
name: lint
on:
  push:
    branches: ["main"]
  pull_request:

permissions:
  contents: read
  # Optional: allow read access to pull request. Use with `only-new-issues` option.
  # pull-requests: read

jobs:
  linters:
    name: "linters"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 1
      - uses: codespell-project/actions-codespell@v2
        with:
          check_filenames: true
          check_hidden: true
      - name: Check spelling of entire workspace
        uses: crate-ci/typos@v1
      - uses: DavidAnson/markdownlint-cli2-action@v20
        with:
          globs: '**/*.md'
